import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow,QLabel
from painting import MainWidget
from new_project import new_project
from opencv import opencv
from Rake_wave import Rake_wave
from reflection_coe import reflection_coe
from synthetic_seismogram import synthetic_seismogram
from spectrum_diagram import spectrum_diagram

class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 574)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1041, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.Tab = QtWidgets.QWidget()
        self.Tab.setObjectName("Tab")
        self.splitter = QtWidgets.QSplitter(self.Tab)
        self.splitter.setGeometry(QtCore.QRect(0, 430, 331, 61))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_5 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_6.setObjectName("pushButton_6")

        self.widget = MainWidget(self.Tab)
        self.widget.setGeometry(QtCore.QRect(360, 10, 650, 500))
        self.widget.setObjectName("widget")

        self.splitter_4 = QtWidgets.QSplitter(self.Tab)
        self.splitter_4.setGeometry(QtCore.QRect(0, 250, 331, 161))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_4.addWidget(self.radioButton_2)
        #combo box
        self.comboBox = QtWidgets.QComboBox(self.Tab)
        self.comboBox.setGeometry(QtCore.QRect(180, 10, 151, 31))
        self.comboBox.setObjectName("comboBox")

        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")


        self.splitter_5 = QtWidgets.QSplitter(self.Tab)
        self.splitter_5.setGeometry(QtCore.QRect(10, 50, 141, 131))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.pushButton = QtWidgets.QPushButton(self.splitter_5)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.splitter_5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.splitter_3 = QtWidgets.QSplitter(self.Tab)
        self.splitter_3.setGeometry(QtCore.QRect(180, 50, 151, 131))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.Tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionda = QtWidgets.QAction(MainWindow)
        self.actionda.setObjectName("actionda")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.menu.addSeparator()
        self.menu.addAction(self.actionda)
        self.menu.addAction(self.action1)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.label.setBuddy(self.lineEdit)
        self.label_3.setBuddy(self.lineEdit_3)
        self.label_2.setBuddy(self.lineEdit_2)
        self.label_4.setBuddy(self.lineEdit_4)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(self.new_project)
        self.pushButton_3.clicked.connect(self.Rake_wave)
        self.pushButton_4.clicked.connect(self.reflection_coe)
        self.pushButton_5.clicked.connect(self.synthetic_seismogram)
        self.pushButton_6.clicked.connect(self.spectrum_diagram)
        #确定边缘检测算法的类型
        self.pushButton_7.clicked.connect(self.opencv)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>1</p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "合成地震记录"))
        self.pushButton_6.setText(_translate("MainWindow", "频谱图"))
        self.label.setText(_translate("MainWindow", "采样时间："))
        self.label_3.setText(_translate("MainWindow", "主频："))
        self.label_2.setText(_translate("MainWindow", "采样率："))
        self.radioButton.setText(_translate("MainWindow", "默认值"))
        self.label_4.setText(_translate("MainWindow", "设置道间距："))
        self.radioButton_2.setText(_translate("MainWindow", "默认值"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Scharr算子"))
        self.comboBox.setItemText(1, _translate("MainWindow", "sobel算子"))
        self.comboBox.setItemText(2, _translate("MainWindow", "log算子"))
        self.pushButton.setText(_translate("MainWindow", "新建正演文件"))
        self.pushButton_4.setText(_translate("MainWindow", "设置反射系数"))
        self.pushButton_7.setText(_translate("MainWindow", "图像识别"))
        self.pushButton_3.setText(_translate("MainWindow", "设置雷克子波"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab), _translate("MainWindow", "正演模拟"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "文件信息读取"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "工具"))
        self.menu_4.setTitle(_translate("MainWindow", "窗口"))
        self.menu_5.setTitle(_translate("MainWindow", "帮助"))
        self.actionda.setText(_translate("MainWindow", "打开文件"))
        self.action1.setText(_translate("MainWindow", "保存文件"))
    #1新建正演项目
    def new_project(self):
        self.ui_1 = new_project()
        self.ui_1.show()
    #2图像识别
    def opencv(self):
        self.type = self.comboBox.currentText()
        self.ui_2 = opencv(self.type)
        self.ui_2.show()
    #3雷克子波
    def Rake_wave(self):
        self.ui_3 = Rake_wave()
        self.ui_3.show()
    #4设置反射系数
    def reflection_coe(self):
        self.ui_4 = reflection_coe()
        self.ui_4.show()
    #5合成地震记录
    def synthetic_seismogram(self):
        self.ui_5 = synthetic_seismogram()
        self.ui_5.show()
    #6频谱图
    def spectrum_diagram(self):
        self.ui_6 = spectrum_diagram()
        self.ui_6.show()
if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())