from PyQt5.QtWidgets import QApplication, QMainWindow,QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import cv2
import json
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

class new_project(QMainWindow):
    def __init__(self, parent=None):
        super(new_project, self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(421, 353)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 220, 411, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.splitter = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter.setGeometry(QtCore.QRect(120, 20, 208, 22))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget_6 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.spinBox_5 = QtWidgets.QSpinBox(self.layoutWidget_6)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_7.addWidget(self.spinBox_5)
        self.layoutWidget_7 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.spinBox_6 = QtWidgets.QSpinBox(self.layoutWidget_7)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_8.addWidget(self.spinBox_6)
        self.layoutWidget_8 = QtWidgets.QWidget(Form)
        self.layoutWidget_8.setGeometry(QtCore.QRect(70, 280, 241, 61))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget_8)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget_8)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 40, 411, 171))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(150, 140, 92, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_5.addWidget(self.spinBox_3)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(150, 20, 92, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.spinBox_4 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_6.addWidget(self.spinBox_4)
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 80, 93, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(290, 80, 92, 22))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget_4)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView.setGeometry(QtCore.QRect(120, 50, 161, 81))
        self.graphicsView.setObjectName("graphicsView")
        self.layoutWidget_5 = QtWidgets.QWidget(Form)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 10, 201, 22))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget_5)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit.setObjectName("lineEdit")
        self.spinBox.setMaximum(9999)
        self.spinBox_2.setMaximum(9999)
        self.spinBox_3.setMaximum(9999)
        self.spinBox_4.setMaximum(9999)
        self.spinBox_5.setMaximum(9999)
        self.spinBox_6.setMaximum(9999)

        self.horizontalLayout.addWidget(self.lineEdit)
        self.retranslateUi(Form)

        self.pushButton.clicked.connect(Form.save)
        self.pushButton_2.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "单元格尺寸"))
        self.label_9.setText(_translate("Form", "宽度（米）"))
        self.label_10.setText(_translate("Form", "高度（米）"))
        self.pushButton.setText(_translate("Form", "保存项目"))
        self.pushButton_2.setText(_translate("Form", "取消"))
        self.groupBox.setTitle(_translate("Form", "网格范围"))
        self.label_7.setText(_translate("Form", "底（米）"))
        self.label_8.setText(_translate("Form", "顶（米）"))
        self.label_5.setText(_translate("Form", "左（米）"))
        self.label_6.setText(_translate("Form", "右（米）"))
        self.label.setText(_translate("Form", "项目名称："))
    def save(self):
        self.name = self.lineEdit.text()
        self.Grid_range = [self.spinBox_4.value(), self.spinBox_3.value(), self.spinBox.value(), self.spinBox_2.value()]
        self.Cell_range = [self.spinBox_5.value(), self.spinBox_6.value()]
        a = {"project_name": "{}".format(self.name),"Grid_range": "{}".format(self.Grid_range),"Cell_range": "{}".format(self.Cell_range)}
        b = json.dumps(a)
        f2 = open('project.json', 'w')
        f2.write(b)
        f2.close()
        QMessageBox.warning(self, " ", "保存成功！", QMessageBox.Yes | QMessageBox.No)
        '''
        app = QApplication(sys.argv)  # 所有pyqt5必须创建一个QApplication对象
        w = QWidget()  # 没有父类的widget将被作为窗口使用
        # 退出确定框
        reply = QMessageBox.question(w, '保存结果', '确定退出？', QMessageBox.Yes | QMessageBox.No | QMessageBox.Cancel,QMessageBox.Cancel)
        if reply == QMessageBox.Yes:
            print('退出')
        else:
            print('不退出')
        '''


